module Swimmy
  module Resource
    dir = File.dirname(__FILE__) + "/resource"

    autoload :Memo,        "#{dir}/memo.rb"
    autoload :Attendance,  "#{dir}/attendance.rb"
    autoload :Place,       "#{dir}/place.rb"
    autoload :Weather,     "#{dir}/weather.rb"
    autoload :Member,      "#{dir}/member.rb"
    autoload :Calendar,    "#{dir}/calendar.rb"
    autoload :Anniversary, "#{dir}/anniversary.rb"
    autoload :Recurrence,  "#{dir}/schedule.rb"
    autoload :Occurence,   "#{dir}/schedule.rb"
    autoload :CoronaInfo,  "#{dir}/coronaresource.rb"
    autoload :Restaurant,  "#{dir}/restaurant.rb"
    autoload :GoogleOAuth, "#{dir}/google_oauth.rb"
    autoload :Event,       "#{dir}/event.rb"
    autoload :Pollen,      "#{dir}/pollen_resource.rb"
    autoload :OpenhabMetadata, "#{dir}/openhab_metadata.rb"
    autoload :CoopShop,         "#{dir}/coop_info.rb"
    autoload :NomnichiArticle,  "#{dir}/nomnichi_article.rb"
    autoload :CookResource, "#{dir}/cook_resource.rb"
    autoload :BookmarkEntry, "#{dir}/bookmark.rb"
    autoload :CalendarEvent, "#{dir}/calendar_event.rb"
    autoload :ArtistInfo , "#{dir}/artist_info.rb"
    autoload :MeetingEvent, "#{dir}/meeting_event.rb"
    autoload :Minutes, "#{dir}/minutes.rb"
    autoload :Homework,    "#{dir}/homework.rb"
    autoload :IdName,      "#{dir}/id_name.rb"
    autoload :Task,        "#{dir}/task.rb"
    autoload :Document,    "#{dir}/document.rb"
    autoload :User,        "#{dir}/user.rb"
    autoload :Project,     "#{dir}/project.rb"
  end
end
